[default]
app_name = "Industrial Data Moscow"
app_version = "0.1.0"
debug = true
host = "0.0.0.0"
port = 8000

[default.database]
host = "localhost"
port = 5432
name = "mosprom_db"
user = "mosprom_user"
password = "mosprom_password"
echo = false
pool_size = 5
max_overflow = 10

[default.logging]
level = "INFO"
log_dir = "logs"
log_file = "mosprom.log"
log_format = "json"
log_to_console = true
log_to_file = true

[default.upload]
max_file_size = 10485760
allowed_extensions = [".xlsx", ".xls"]
upload_dir = "uploads"

[default.pagination]
default_page_size = 50
max_page_size = 1000

[default.fns_api]
api_key = ""
enabled = true
timeout = 30

[production]
debug = false

[production.logging]
level = "WARNING"

[development]
debug = true

[development.database]
echo = true

[development.logging]
level = "DEBUG"
