"""empty message

Revision ID: c587b49c593d
Revises: 
Create Date: 2025-10-17 19:36:47.967455+03:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c587b49c593d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("industry", sa.String(length=200), nullable=True),
        sa.Column("sub_industry", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_index(op.f("ix_organizations_industry"), "organizations", ["industry"], unique=False)
    op.create_index(op.f("ix_organizations_inn"), "organizations", ["inn"], unique=True)
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_table(
        "organization_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.Column("export_volume", sa.Float(), nullable=True),
        sa.Column("investments", sa.Float(), nullable=True),
        sa.Column("payroll_fund", sa.Float(), nullable=True),
        sa.Column("average_salary", sa.Float(), nullable=True),
        sa.Column("employees_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_org_metrics_org_year", "organization_metrics", ["organization_id", "year"], unique=False
    )
    op.create_index(
        op.f("ix_organization_metrics_id"), "organization_metrics", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_metrics_year"), "organization_metrics", ["year"], unique=False
    )
    op.drop_table("test_table")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_table",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("test_table_pkey")),
    )
    op.drop_index(op.f("ix_organization_metrics_year"), table_name="organization_metrics")
    op.drop_index(op.f("ix_organization_metrics_id"), table_name="organization_metrics")
    op.drop_index("ix_org_metrics_org_year", table_name="organization_metrics")
    op.drop_table("organization_metrics")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_inn"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_industry"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
